import AuthProvider from "@/components/AuthProvider";
import Header from "@/components/layout/Header";
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <main className="max-w-4xl border mx-auto p-1 ">
           <AuthProvider>
           <Header />
          {children}
           </AuthProvider>
        </main>
      </body>
    </html>
  );
}
